export const USER_REGISTRATION = "USER_REGISTRATION";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_STATUS = "USER_LOGIN_STATUS";

export const GET_COUNTRY = "GET_COUNTRY";
export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS";
export const GET_COUNTRY_FAIL = "GET_COUNTRY_FAIL";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL";
// HAWALA LIST
export const HAWALA_LIST = "HAWALA_LIST";
export const GET_HAWALA_LIST_SUCCESS = "GET_HAWALA_LIST_SUCCESS";
export const GET_HAWALA_LIST_FAIL = "GET_HAWALA_LIST_FAIL";

//GET Transaction List

export const CLIENT_LIST = "CLIENT_LIST";
export const GET_CLIENT_LIST_SUCCESS = "GET_CLIENT_LIST_SUCCESS";
export const GET_CLIENT_LIST_FAIL = "GET_CLIENT_LIST_FAIL";

// Get Deposite DETAILS

export const DEPOSIT_DETAIL = "DEPOSIT_DETAIL";
export const GET_DEPOSIT_DETAIL_SUCCESS = "GET_DEPOSIT_DETAIL_SUCCESS";
export const GET_DEPOSIT_DETAIL_FAIL = "GET_CLIENT_LIST_FAIL";

// empty user state after submit of otp

export const EMPTY_USER = "EMPTY_USER";

//send otp after success registration

export const SEND_OTP = "SEND_OTP";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAIL = "SEND_OTP_FAIL";

//verify otp on registration

export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";


export const REQUEST_DEPOSIT = "REQUEST_DEPOSIT";
export const REQUEST_DEPOSIT_SUCCESS = "REQUEST_DEPOSIT_SUCCESS";
export const REQUEST_DEPOSIT_FAIL = "REQUEST_DEPOSIT_FAIL";

// GET WALLET BALANCE

export const GET_WALLET_BALANCE = "GET_WALLET_BALANCE";
export const GET_WALLET_BALANCE_SUCCESS = "GET_WALLET_BALANCE_SUCCESS";
export const GET_WALLET_BALANCE_FAIL = "GET_WALLET_BALANCE_FAIL";
//WITHDRAW_REQUEST
export const WITHDRAW_REQUEST = "WITHDRAW_REQUEST";
export const WITHDRAW_REQUEST_SUCCESS = "WITHDRAW_REQUEST_SUCCESS";
export const WITHDRAW_REQUEST_FAIL = "GET_WALLET_BALANCE_FAIL";
//Get transaction Details
export const GET_TRANSACTIONS_LIST = "GET_TRANSACTIONS_LIST";
export const GET_TRANSACTIONS_LIST_SUCCESS = "GET_TRANSACTIONS_LIST_SUCCESS";
export const GET_TRANSACTIONS_LIST_FAIL = "GET_TRANSACTIONS_LIST_FAIL";

//Change Password 

export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";

// third party transaction

export const THIRD_PARTY_TRANSACTION = "THIRD_PARTY_TRANSACTION";
export const THIRD_PARTY_TRANSACTION_SUCCESS = "THIRD_PARTY_TRANSACTION_SUCCESS";
export const THIRD_PARTY_TRANSACTION_FAIL = "THIRD_PARTY_TRANSACTION_FAIL";


// change passowrd
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const BECOME_DEALER_REQUEST = "BECOME_DEALER_REQUEST";
